export {
  fallbackSiteData,
  getDestinations,
  getDestinationsPage,
  getHomePage,
  getHome,
  getHomeStaticProps,
  getInfo,
  getInfoStaticProps,
  getJuryMembers,
  getJuryPage,
  getPage,
  getPageDeadlines,
  getOpenCallPage,
  getSite,
} from "./sanity/fetch";
